### ISSUE TITLE
User Search

### ISSUE THREAD

**Issue by lazyguru** [kalenjordan/magehero#108]
It would be really nice if there was a way to search for users by name.  I've been using MageHero to help find people Phil and Kalen mention on MageTalk to get their Twitter handle, etc..  I have to click "Load More" a bunch of times and then search the page.

**Comment by kalenjordan** [comment]
Totally +1.

(side note: is this the kind of +1 you can't stand?  #soconfused)

**Comment by lazyguru** [comment]
Yes. Remind me when we see each other at Imagine that I owe you a slap ;-)

**Comment by kalenjordan** [comment]
So you'd rather I left your comment dangling with no response rather than a sweet +1?  You make no sense.  Also: you are dead to me.  Also: I will be prepared, will dodge the slap, and sweep the leg.  Samurai code number 1: always be ready.

**Comment by lazyguru** [comment]
You will not know the day or the hour of the slap. I studied HIMYM very carefully and know the power of a foretold slap.

**Comment by lazyguru** [comment]
On a side note, if I ever get my local copy working again I do plan on trying to add this feature. So if someone else decides to work on it, please let me know.

**Comment by bobbyshaw** [comment]
@lazyguru I've knocked this out this morning before the hackathon.  I'd welcome a review https://github.com/kalenjordan/magehero/pull/109

**Comment by lazyguru** [comment]
#109 looks good
