### ISSUE TITLE
Email notifications when someone comments on a post

### ISSUE THREAD

**Issue by kalenjordan** [kalenjordan/magehero#116]
We had enabled this before but ran into issues.  Going to try changing the GET to a POST in the disqus callback.  Also going to add some light logging of outgoing emails so we can troubleshoot if it starts sending too many emails again.

**Comment by navarr** [comment]
I got an email on May 9th from this system.  Is this "done"?

**Comment by kalenjordan** [comment]
Yes!  Thanks for the reminder.
