### ISSUE TITLE
The domain is marked as inactive?

### ISSUE THREAD

**Issue by Rud5G** [kalenjordan/magehero#134]
Is the site still online or did the URL change? 

Because, at the moment i get the notification: "The domain is marked as inactive" at http://magehero.com/ )

**Comment by kalenjordan** [comment]
Yes unfortunately the domain expired and @danslo still owns it - I've asked him if he could help to transfer/renew it but haven't been able to get that worked out yet.  Working on it.

**Comment by kalenjordan** [comment]
For reference:
https://twitter.com/kalenjordan/status/659010731044663296
https://twitter.com/kalenjordan/status/660854855754379265

**Comment by kalenjordan** [comment]
It's back up.
