### ISSUE TITLE
Sorry! Not the place I know... 

### ISSUE THREAD

**Issue by jonathonbyrdziak** [kalenjordan/magehero#135]
@kalenjordan Any chance I could pay you to pin my latest post to the homepage? http://magehero.com/posts/1111/how-i-m-creating-the-uber-of-the-magento-developer-community

**Comment by kalenjordan** [comment]
@Jonathonbyrd looks interesting - I'll give this a read!!

**Comment by kalenjordan** [comment]
Just popped you an email @Jonathonbyrd !
