### ISSUE TITLE
Array to string conversion issue

### ISSUE THREAD

**Issue by benmarks** [kalenjordan/magehero#87]
[`Model_User::getDetail()`](https://github.com/benmarks/magehero/blob/master/code/Model/User.php#L221) has a mixed return type (explicitly `array` or `null` or the decoded type value) which is not considered by calling code.

When `details_json` cannot be decoded in `::getDetail()` an empty array is returned. This results in an "array to string conversion" notice in [ `Model_User:: getGithubUsername()`](https://github.com/benmarks/magehero/blob/master/code/Model/User.php#L199). Currently this notice is visible in the */users* and */map/users* routes.

I'll submit a patch which will handles the case of `json_decode` failure by returning `null`.

**Comment by kalenjordan** [comment]
BENJAMIN H MARKS!  Thank you sir.  Does this happen when you run the app/console script?

**Comment by benmarks** [comment]
@kalenjordan see http://magehero.com/map/users

![screen shot 2015-01-02 at 1 50 55 pm](https://cloud.githubusercontent.com/assets/2141138/5598551/7547cf6a-9286-11e4-92f7-962471aadc97.png)

**Comment by bobbyshaw** [comment]
Cheers Ben. It'll be nice when we finally move away from that Jason Blob.

**Comment by kalenjordan** [comment]
Awesome thanks Ben.  Also I just disabled errors in production.  Exceptions had been disabled in production but now errors are too.  That was no good at all.  

So that actually resolves the issue for now as well but we'll get this merged in soon too.
