### ISSUE TITLE
Blank PHPSESSID issue

### ISSUE THREAD

**Issue by tegansnyder** [kalenjordan/magehero#89]
I'm not sure if it's just me, but I wanted to share this in case anyone else has experience the same issue. This is a screenshot of me logged out with some PHP warnings:
![magehero___awesome_magento_developers](https://cloud.githubusercontent.com/assets/1200195/5599827/0c3844a6-9294-11e4-8bc3-08d640f25228.png)

I quick search found this:
https://bugs.php.net/bug.php?id=68063

I can see from cookies panel I have a blank PHPSESSID as a cookie. I'm not really sure how it happened. If I clear my cookies everything works perfectly and the site functions as expected.
![pasted_image_1_2_15__3_35_pm](https://cloud.githubusercontent.com/assets/1200195/5599863/a2f23db6-9294-11e4-97ce-5f8d4ebcd215.png)

Apparently you can mitigate around this by:
```php
$ok = @session_start();
if(!$ok){
session_regenerate_id(true); // replace the Session ID
session_start(); 
}
```

**Comment by kalenjordan** [comment]
Crazy.  Ya let's put that fix in place.  Maybe you could pr that when you
get a sec.

On Fri, Jan 2, 2015 at 1:34 PM, Tegan Snyder <notifications@github.com>
wrote:

> I'm not sure if it's just me, but I wanted to share this in case anyone
> else has experience the same issue. This is a screenshot of me logged out
> with some PHP warnings:
> [image: magehero___awesome_magento_developers]
> <https://cloud.githubusercontent.com/assets/1200195/5599827/0c3844a6-9294-11e4-8bc3-08d640f25228.png>
>
> I quick search found this:
> https://bugs.php.net/bug.php?id=68063
>
> I can see from cookies panel I have a blank PHPSESSID as a cookie. I'm not
> really sure how it happened. If I clear my cookies everything works
> perfectly and the site functions as expected.
> [image: pasted_image_1_2_15__3_35_pm]
> <https://cloud.githubusercontent.com/assets/1200195/5599863/a2f23db6-9294-11e4-97ce-5f8d4ebcd215.png>
>
> Apparently you can mitigate around this by:
>
> $ok = @session_start();if(!$ok){session_regenerate_id(true); // replace the Session IDsession_start(); }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kalenjordan/magehero/issues/89>.
>



-- 
Kalen Jordan
Founder, MageMail

Listen to MageTalk - The Magento Podcast <http://magetalk.com/> | MageMail
- The Triggered Email App for Magento
<http://magemail.co/?utm_medium=email&utm_source=signature&utm_campaign=signature>
