### ISSUE TITLE
mageupdate.com showing magehero site. 

### ISSUE THREAD

**Issue by bobbyshaw** [kalenjordan/magehero#92]
Looks like your mageupdate.com site is on the same server and is showing content for magehero.com.  Noticed it in google search results so would be good to get this sorted!

**Comment by kalenjordan** [comment]
I defaulted that domain back to godaddy.com default name servers.  Should fix it I think.

**Comment by bobbyshaw** [comment]
I see the change, thanks.

**Comment by kalenjordan** [comment]
I realized that I still have some email pointing to mageupdate.com (woops!).  So I repointed the domain to my server, but I'm going to setup a web root or something in order to avoid it pointing to magehero.com

**Comment by bobbyshaw** [comment]
Seems like you've done something to not show magehero on mageupdate.  That mean we can close this again?

![screen shot 2015-01-09 at 16 53 49](https://cloud.githubusercontent.com/assets/553566/5683482/2b129e12-9820-11e4-8c7a-948ade01d5f0.png)

**Comment by kalenjordan** [comment]
Yep - sorry forgot to close!

**Comment by bobbyshaw** [comment]
No worries, thanks :)
